# This is a basic workflow to help you get started with Actions

name: Linux Examples

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "**.h"
      - "**.hpp"
      - "**.c"
      - "**.cc"
      - "**.cpp"
      - "**.py"
      - ".github/workflows/main.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_examples:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          architecture: 'x64'
      # Install xorg-dev libgl1-mesa-dev clang-9
      - name: Install Dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y -qq clang-9 gcc-10 g++-10
      # Checkout Confply
      - name: Checkout code
        uses: actions/checkout@v2
      # Cpp_compiler examples
      - name: Cpp_compiler.py clang++
        run: python test.py clang++
        if: ${{ always() }}
      # Cpp_compiler examples
      - name: Cpp_compiler.py clang
        run: python test.py clang
        if: ${{ always() }}
      # Cpp_compiler examples
      - name: Cpp_compiler.py g++
        run: python test.py g++
        if: ${{ always() }}
      # Cpp_compiler examples
      - name: Cpp_compiler.py gcc
        run: python test.py gcc
        if: ${{ always() }}

