name: Windows Examples

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "**.h"
      - "**.hpp"
      - "**.c"
      - "**.cc"
      - "**.cpp"
      - "**.py"
      - ".github/workflows/main.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_examples:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          architecture: 'x64'
      # Checkout Confply
      - name: Checkout code
        uses: actions/checkout@v2
      # Cpp_compiler examples
      - name: Cpp_compiler.py cl
        run: python test.py cl
        if: ${{ always() }}
      # Cpp_compiler examples
      - name: Cpp_compiler.py gcc
        run: python test.py gcc
        if: ${{ always() }}
      # Cpp_compiler examples
      - name: Cpp_compiler.py g++
        run: python test.py g++
        if: ${{ always() }}
      # Test --new_tool
      - name: --new_tool
        run: python confply.py --new_tool my_tool
        if: ${{ always() }}
      - name: --new_config
        run: python confply.py --new_config my_tool my_tool.py
        if: ${{ always() }}
      - name: Run my_tool
        run: python confply.py my_tool.py
        if: ${{ always() }}
